'use server';

/**
 * @fileOverview This file defines a Genkit flow to generate synthetic news content for a stock
 * when the primary data source is unavailable.
 *
 * - generateSyntheticNews - A function that takes a stock ticker and returns generated news.
 * - GenerateSyntheticNewsInput - The input type for the function.
 * - GenerateSyntheticNewsOutput - The output type for the function.
 */

import { ai } from '@/ai/index';
import { z } from 'zod';

const GenerateSyntheticNewsInputSchema = z.object({
  ticker: z.string().describe('The stock ticker symbol.'),
});
export type GenerateSyntheticNewsInput = z.infer<typeof GenerateSyntheticNewsInputSchema>;

const GenerateSyntheticNewsOutputSchema = z.object({
  headlines: z.array(z.string()).describe('An array of 3-4 plausible but synthetic news headlines.'),
  summary: z.string().describe('A brief, general summary paragraph about the current (fictional) state of the stock.'),
  disclaimer: z.string().describe('A mandatory disclaimer stating the content is AI-generated.'),
});
export type GenerateSyntheticNewsOutput = z.infer<typeof GenerateSyntheticNewsOutputSchema>;


export async function generateSyntheticNews(
  input: GenerateSyntheticNewsInput
): Promise<GenerateSyntheticNewsOutput> {
  return generateSyntheticNewsFlow(input);
}


const generateSyntheticNewsPrompt = ai.definePrompt({
  name: 'generateSyntheticNewsPrompt',
  input: { schema: GenerateSyntheticNewsInputSchema },
  output: { schema: GenerateSyntheticNewsOutputSchema },
  prompt: `You are a financial news summarizer AI. The primary data source for real-time news is currently unavailable. Your task is to generate a plausible but entirely **fictional** set of news headlines and a summary for the stock ticker {{ticker}}.

**Instructions:**
1.  Invent 3-4 realistic-sounding news headlines. The headlines should cover different aspects like earnings, product launches, market sentiment, or analyst ratings.
2.  Write a short summary paragraph (2-3 sentences) that synthesizes the fictional events from your headlines into a coherent narrative.
3.  The tone should be professional and resemble that of a real financial news outlet.
4.  Crucially, you **MUST** include the following text verbatim in the 'disclaimer' field: "The following news is synthetically generated by AI as a placeholder because the live news service is currently unavailable. It is not real news and should not be used for investment decisions."

Do not use real, current events. This is a creative writing task based on the persona of a financial analyst.
`,
});

const generateSyntheticNewsFlow = ai.defineFlow(
  {
    name: 'generateSyntheticNewsFlow',
    inputSchema: GenerateSyntheticNewsInputSchema,
    outputSchema: GenerateSyntheticNewsOutputSchema,
  },
  async (input) => {
    const { output } = await generateSyntheticNewsPrompt(input);
    return output!;
  }
);
